# Listen on all interfaces
interface=eth0
bind-interfaces

# Forward all other DNS queries to Google
server=8.8.8.8

# Redirect EMO API to your local machine
address=/api.living.ai/192.168.1.109
address=/eu-api.living.ai/192.168.1.109
address=/tts.living.ai/192.168.1.109
address=/eu-tts.living.ai/192.168.1.109
address=/res.living.ai/192.168.1.109
address=/res-eu.living.ai/192.168.1.109
address=/us-api.living.ai/192.168.1.109
address=/as-api.living.ai/192.168.1.109
address=/res-us-east-1.living.ai/192.168.1.109
address=/res-eu-central-1.living.ai/192.168.1.109
address=/res-ap-southeast-1.living.ai/192.168.1.109
address=/res-cn-shenzhen.living.ai/192.168.1.109

# Log everything
log-queries
log-facility=-
