services:
  homeassistant:
    container_name: homeassistant
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "5"
    dns:
    - 8.8.8.8
    - 1.1.1.1
    environment:
    - TZ=Europe/Minsk
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
    - ha-data:/config
    - /run/dbus:/run/dbus:ro
  matter-server:
    container_name: matter-server
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "3"
    environment:
    - MATTER_SERVER__INSTANCE_NAME=Matter
    - MATTER_SERVER__PORT=5580
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    network_mode: host
    restart: unless-stopped
    volumes:
    - matter-data:/data
  mosquitto:
    container_name: mosquitto
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "3"
    image: eclipse-mosquitto:2
    ports:
    - 1883:1883
    restart: unless-stopped
    volumes:
    - mosquitto-data:/mosquitto/data
    - mosquitto-config:/mosquitto/config
  zigbee2mqtt:
    container_name: zigbee2mqtt
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "3"
    devices:
    - /dev/ttyACM0:/dev/ttyACM0
    environment:
    - TZ=Europe/Minsk
    image: koenkk/zigbee2mqtt
    network_mode: host
    restart: unless-stopped
    volumes:
    - z2m-data:/app/data
    - /run/udev:/run/udev:ro
volumes:
  ha-data: null
  matter-data: null
  mosquitto-config: null
  mosquitto-data: null
  z2m-data: null
