services:
  coral-vision:
    container_name: coral-vision
    environment:
    - PORT=8090
    image: ghcr.io/satsura/coral-vision:latest
    network_mode: host
    ports:
    - 8090:8090
    privileged: true
    restart: unless-stopped
    volumes:
    - /dev/bus/usb:/dev/bus/usb
  hik-watcher:
    build: ../hikvision
    container_name: hik-watcher
    environment:
    - PORT=8092
    - NVR_IP=192.168.1.180
    - HIK_USER=admin
    - HIK_PASS=911HPExp
    - TG_TOKEN=8532330447:AAHyf13dH1ySXqrLbLftrQNtgdS3XTjkYYc
    - TG_CHAT_ID=405695817
    - CORAL_URL=http://127.0.0.1:8090/detect?lang=ru&threshold=0.3
    - N8N_WEBHOOK=http://127.0.0.1:5678/webhook/cameras_v2/webhook/cam
    - COOLDOWN=10
    network_mode: host
    restart: unless-stopped
  homeassistant:
    container_name: homeassistant
    dns:
    - 8.8.8.8
    - 1.1.1.1
    environment:
    - TZ=Europe/Minsk
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
    - ha-data:/config
    - /run/dbus:/run/dbus:ro
  matter-server:
    container_name: matter-server
    environment:
    - MATTER_SERVER__INSTANCE_NAME=Matter
    - MATTER_SERVER__PORT=5580
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    network_mode: host
    restart: unless-stopped
    volumes:
    - matter-data:/data
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    ports:
    - 1883:1883
    restart: unless-stopped
    volumes:
    - mosquitto-data:/mosquitto/data
    - mosquitto-config:/mosquitto/config
  n8n:
    container_name: n8n
    environment:
    - N8N_PORT=5678
    - N8N_PROTOCOL=http
    - WEBHOOK_URL=http://192.168.1.109:5678
    - N8N_BASIC_AUTH_ACTIVE=true
    - N8N_BASIC_AUTH_USER=admin
    - N8N_BASIC_AUTH_PASSWORD=emo2024
    - N8N_SECURE_COOKIE=false
    - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
    - EXECUTIONS_DATA_SAVE_ON_ERROR=all
    - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
    image: n8nio/n8n:latest
    network_mode: host
    restart: unless-stopped
    volumes:
    - n8n-data:/home/node/.n8n
    - /home/valera/emo-photos:/photos
  zigbee2mqtt:
    container_name: zigbee2mqtt
    devices:
    - /dev/ttyACM0:/dev/ttyACM0
    environment:
    - TZ=Europe/Minsk
    image: koenkk/zigbee2mqtt
    network_mode: host
    restart: unless-stopped
    volumes:
    - z2m-data:/app/data
    - /run/udev:/run/udev:ro
volumes:
  ha-data: null
  matter-data: null
  mosquitto-config: null
  mosquitto-data: null
  n8n-data: null
  z2m-data: null
